__NUMPY__

1. NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. <br>
2. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems.<br> 
3. NumPy users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development.<br> 
4. The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.<br>

In [2]:
import numpy as np


In [3]:
np.dtype

numpy.dtype

In [4]:
a=np.arange(6)

In [5]:
a

array([0, 1, 2, 3, 4, 5])

In [6]:
a2 = a[np.newaxis, :]


In [7]:
a2.shape

(1, 6)

In [8]:
a=np.array([1,2,3,4,5,6,7,8])


In [9]:
print(a)

[1 2 3 4 5 6 7 8]


In [10]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [11]:
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
print(a[2])

3


In [13]:
print(a2[1])

[ 6  7  8  9 10]


- The Numpy uses ndarray
- ndarray is a class numpy
- 1D -> vector
- 2D -> Matrix
- 3D -> Tensor
- In Numpy dimensions are called as axes

In [14]:
a=np.array([1,2,3])

In [15]:
a


array([1, 2, 3])

In [16]:
#to create a zero array
np.zeros(2)

array([0., 0.])

In [17]:
#to create a ones array
np.ones(2)

array([1., 1.])

In [18]:
#to create a two dim array
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [19]:
# to create a empty array it gives random values
np.empty(4)

array([1., 1., 1., 1.])

In [20]:
# to create  a a range of elements 
np.arange(4)

array([0, 1, 2, 3])

In [21]:
#np.arange(firstno,lastno-1,step size)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [22]:
np.linspace(0,10,num=8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [23]:
#default data type is floating point (np.float64) to specify data type use dtype
x=np.ones(2,dtype=np.int64)

In [24]:
print(x)

[1 1]


# Adding, removing and sorting elements

In [25]:
arr=np.array([9,7,3,2,1,4,5,67,9])

In [26]:
print(np.sort(arr))

[ 1  2  3  4  5  7  9  9 67]


- np.sort(a,axis=-1,kind=None,order=None)
- kind :{‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}
- order : When a is an array with fields defined, this argument specifies which fields to compare first, second, etc. A single field can be specified as a string, and not all fields need be specified, but unspecified fields will still be used, in the order in which they come up in the dtype, to break ties.

In [27]:
#np.concatenate()
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [28]:
c=np.concatenate((a,b))

In [29]:
print(c)

[1 2 3 4 5 6 7 8]


In [30]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [31]:
z=np.concatenate((x, y), axis=0)

In [32]:
print(z)

[[1 2]
 [3 4]
 [5 6]]


# shape size and ndim

- ndarray.ndim will tell you the number of axes, or dimensions, of the array.
- ndarray.size will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.
- ndarray.shape will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [33]:
c.ndim

1

In [34]:
z.ndim

2

In [35]:
z.size

6

In [36]:
z.shape

(3, 2)

# reshape

In [37]:
# arr.reshape() is used to reshape a array
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
aa=a.reshape(3,3)

In [39]:
aa

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
aa.ndim

2

In [41]:
aa.shape

(3, 3)

# How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [42]:
a=np.array([i for i in range(1,11) ])

In [43]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [44]:
a2=a[np.newaxis,:]

In [45]:
print(a2)

[[ 1  2  3  4  5  6  7  8  9 10]]


In [46]:
a2.shape

(1, 10)

In [47]:
a2.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [48]:
a3=a[:,np.newaxis]

In [49]:
print(a3)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [50]:
a3.shape

(10, 1)

## np.expand_dims

In [51]:
b=np.expand_dims(a,axis=0)

In [52]:
b


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [53]:
c=np.expand_dims(a,axis=1)

In [54]:
c


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

# Indexing and slicing


In [55]:
a=np.array([i for i in range(1,11) ])

In [56]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
a.shape

(10,)

In [58]:
a[6]

7

In [59]:
a[1:9]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a[2:6]

array([3, 4, 5, 6])

In [61]:
a[-2]

9

In [62]:
a[-2:]

array([ 9, 10])

In [63]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [64]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
a[1,1]

6

In [66]:
a[2,3]

12

In [83]:
a=np.array([i for i in range(1,11)])

In [84]:
b=np.save('sample',a)

In [86]:
c=np.load('sample.npy')

In [87]:
c


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])